name: Build Vencord Addon

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Vencord
        uses: actions/checkout@v4.2.2
        with:
          repository: Vendicated/Vencord

      - name: Setup Node.JS
        uses: actions/setup-node@v4.2.0

      - name: Build
        run: |
          npm i -g pnpm web-ext
          pnpm i
          pnpm run buildWeb
          jq '.browser_specific_settings.gecko.id = "addon@'$(mktemp -u XXXXXX)'"' dist/firefox-unpacked/manifest.json > tmp.json
          mv tmp.json dist/firefox-unpacked/manifest.json
          web-ext sign -s dist/firefox-unpacked --api-key=${{ secrets.MOZILLA_API_KEY }} --api-secret=${{ secrets.MOZILLA_API_SECRET }} --channel=unlisted
          echo -n "VENCORD_COMMIT=" >> $GITHUB_ENV
          curl https://api.github.com/repos/Vendicated/Vencord/commits/main | jq -r .sha >> $GITHUB_ENV

      - name: Upload Artifact to Releases
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: dist/*.xpi
          tag_name: vencord-${{ env.VENCORD_COMMIT }}
          token: ${{ secrets.RELEASE_TOKEN }}
          name: ${{ env.VENCORD_COMMIT }}
          token: ${{ secrets.RELEASE_TOKEN }}
