name: Build Vencord Addon

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout VenCord
        uses: actions/checkout@v4.2.2
        with:
          repository: Vendicated/Vencord

      - name: Setup Node.JS
        uses: actions/setup-node@v4.2.0

      - name: Build
        run: |
          npm i -g pnpm web-ext
          pnpm i
          pnpm run buildWeb
          jq '.browser_specific_settings.gecko.id = "addon@'$(mktemp -u XXXXXX)'"' dist/firefox-unpacked/manifest.json > tmp.json
          mv tmp.json dist/firefox-unpacked/manifest.json
          web-ext sign -s $ROOT/dist/firefox-unpacked --api-key=${{ secrets.MOZILLA_API_KEY }} --api-secret=${{ secrets.MOZILLA_API_SECRET }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          path: dist/web-ext-artifacts/*.xpi
